{% set name = "llama.cpp" %}
{% set version = "0.0.1641" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ggerganov/llama.cpp/archive/b{{ version.split(".")[-1] }}.tar.gz
  sha256: 8316dfaa8988c444c43ecdcfee535bc6f7c2a7f6ed1c01da45927483ead801b2
  patches:
    - osx-64-pick-discrete.patch  # [osx]
    - mkl.patch                   # [blas_impl == "mkl"]

build:
  number: 0
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_{{ blas_impl }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                 # [(osx and x86_64) or cuda_compiler_version == "None"]
  string: mps_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                 # [osx and arm64]

  script:
    - LLAMA_ARGS="-DLLAMA_BUILD_TESTS=OFF"              # [unix]
    - set LLAMA_ARGS=-DLLAMA_BUILD_TESTS=OFF            # [win]
    {% macro llama_args(value) -%}
    - LLAMA_ARGS="${LLAMA_ARGS} -DLLAMA_{{ value }}"    # [unix]
    - set LLAMA_ARGS=%LLAMA_ARGS% -DLLAMA_{{ value }}   # [win]
    {%- endmacro %}
    {% macro cmake_args(value) -%}
    - LLAMA_ARGS="${LLAMA_ARGS} -D{{ value }}"          # [unix]
    - set LLAMA_ARGS=%LLAMA_ARGS% -D{{ value }}         # [win]
    {%- endmacro %}

    {{ cmake_args("BUILD_SHARED_LIBS=ON") }}

    {{ llama_args("NATIVE=OFF") }}      # [(osx and arm64) or win]
    {{ llama_args("AVX=OFF") }}         # [osx and arm64]
    {{ llama_args("AVX2=OFF") }}        # [osx and arm64]
    {{ llama_args("FMA=OFF") }}         # [osx and arm64]
    {{ llama_args("F16C=OFF") }}        # [osx and arm64]
    {{ llama_args("METAL=ON") }}        # [osx and arm64]
    {{ llama_args("METAL=OFF") }}       # [osx and x86_64]
    {{ llama_args("ACCELERATE=ON") }}   # [osx]
    {{ llama_args("CUBLAS=ON") }}       # [cuda_compiler_version != "None"]

    {{ llama_args("BLAS=ON") }}                        # [not osx and cuda_compiler_version == "None"]
    {{ llama_args("BLAS_VENDOR=Intel10_64_dyn") }}     # [blas_impl == "mkl"]

    - echo $LLAMA_ARGS  # [unix]
    - set LLAMA_ARGS    # [win]

    - cmake -S . -B build -G Ninja %CMAKE_ARGS% %LLAMA_ARGS%    # [win]
    - cmake -S . -B build -G Ninja ${CMAKE_ARGS} ${LLAMA_ARGS}  # [unix]
    - cmake --build build
    - cmake --install build 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - git
    - ninja
    # Required to find mkl on windows
    - pkgconfig  # [win and blas_impl == "mkl"]
  host:
    - cuda-cudart-dev  # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev    # [(cuda_compiler_version or "").startswith("12")]

    - blas-devel * *{{ blas_impl }}  # [blas_impl == "mkl"]
    - mkl-devel {{ mkl }}            # [blas_impl == "mkl"]
  run:
    - cuda-version {{ cuda_compiler_version }}  # [not cuda_compiler_version.startswith("12")]
    - cuda-cudart  {{ cuda_compiler_version }}  # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart_{{ target_platform }} {{ cuda_compiler_version }}  # [(cuda_compiler_version or "").startswith("12") and win]

    - llvm-openmp                    # [linux and blas_impl == "mkl"]

test:
  commands:
    - main --help
    - server --help

about:
  home: https://github.com/ggerganov/llama.cpp
  summary: Port of Facebook's LLaMA model in C/C++
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
